apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-ms-cancelamento-dados
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-ms-cancelamento-dados
  template:
    metadata:
      labels:
        app: tech-ms-cancelamento-dados
    spec:
      containers:
      - name: tech-ms-cancelamento-dados
        image: wviegas/tech-ms:ms-cancelamento-img
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "1.0"
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: my-config-cancelamento
      # imagePullSecrets:
      # - name: regcred
        
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: techchallenge-microservico-pedido-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: techchallenge-microservico-pedido
#   minReplicas: 1
#   maxReplicas: 2
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 60
