apiVersion: v1
kind: Service
metadata:
  name: tech-ms-cancelamento-dados
spec:
  selector:
    app: tech-ms-cancelamento-dados
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: NodePort

